#!/usr/bin/env python3
"""
TossIt Data Models — Content-Addressed Chunk Storage

Architecture:
  Files   = logical objects (UUID v7 ID, user-facing)
  Chunks  = canonical content-addressed blobs (SHA-256 PK, single source of truth)
  FileChunks    = ordered mapping from files → chunks
  ChunkLocations = which nodes physically store which chunks
  RaftLogEntry  = append-only Raft operation log (Phase 1+)

Key principles:
  - File identity is a UUID v7 — time-ordered, globally unique, generated by any
    node without coordination. No leader needed to hand out IDs. No collision risk
    on leader failover or simultaneous uploads across nodes.
  - Chunk identity IS its content hash, globally unique and immutable.
  - Same data → same chunk_hash everywhere. Different data → different hash.
  - The Chunk table is the authoritative record of chunk existence.
  - FileChunk and ChunkLocation both FK to Chunk.chunk_hash.
  - node_id is always the node's cryptographic ID (Ed25519 public key hash),
    never a hardcoded integer. "self" is determined at runtime.
  - RaftLogEntry is append-only. Entries are never updated, only marked applied.
    All non-deterministic values (timestamps, UUIDs) are baked in at propose time
    on the leader so apply is a pure function.
"""

from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, Text,
    Enum as SQLEnum, ForeignKey, UniqueConstraint, Index
)
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime, timezone
import enum


Base = declarative_base()


# ================================================================
#  Enums
# ================================================================

class NodeStatus(enum.Enum):
    ONLINE = "online"
    OFFLINE = "offline"
    MAINTENANCE = "maintenance"


class JobStatus(enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class JobType(enum.Enum):
    REPLICATION = "replication"
    DELETION = "deletion"
    MIGRATION = "migration"


# ================================================================
#  Node — physical machine in the cluster
# ================================================================

class Node(Base):
    __tablename__ = 'nodes'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    ip_address = Column(String, nullable=False)
    port = Column(Integer, default=8000)
    total_capacity_gb = Column(Float, default=0.0)
    free_capacity_gb = Column(Float, default=0.0)
    cpu_score = Column(Float, default=1.0)
    network_speed_mbps = Column(Float, default=100.0)
    avg_uptime_percent = Column(Float, default=100.0)
    status = Column(SQLEnum(NodeStatus), default=NodeStatus.ONLINE)
    last_heartbeat = Column(DateTime, default=lambda: datetime.now(timezone.utc))


# ================================================================
#  File — logical file object (UUID v7, user-facing)
#
#  id is a UUID v7 string rather than a SQLite autoincrement integer.
#  UUID v7 encodes a millisecond timestamp in the high bits, so records
#  sort chronologically by ID with no extra created_at index needed.
#  Any node can generate one independently — no leader coordination,
#  no collision risk on failover or concurrent uploads across nodes.
# ================================================================

class File(Base):
    __tablename__ = 'files'

    id = Column(String(36), primary_key=True)          # UUID v7, e.g. "019035a2-..."
    filename = Column(String, nullable=False)
    total_size_bytes = Column(Integer, nullable=False)
    chunk_size_bytes = Column(Integer, default=8 * 1024 * 1024)
    total_chunks = Column(Integer, nullable=False)
    checksum_sha256 = Column(String, nullable=False)
    is_complete = Column(Boolean, default=False)
    is_replicated = Column(Boolean, default=False)
    uploaded_by = Column(String, default='unknown')
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationship to ordered chunk mappings
    chunk_mappings = relationship("FileChunk", back_populates="file",
                                  order_by="FileChunk.chunk_index",
                                  cascade="all, delete-orphan")


# ================================================================
#  Chunk — canonical content-addressed blob
#
#  The PRIMARY KEY is the SHA-256 hash of the chunk bytes.
#  This is the single source of truth for chunk existence.
#  Every FileChunk and ChunkLocation points here via FK.
#
#  refcount is maintained by the application layer:
#    incremented when a new FileChunk references this hash,
#    decremented when a FileChunk is removed (file deletion).
#  When refcount hits 0, the chunk is eligible for garbage collection
#  (physical deletion from disk + row removal).
# ================================================================

class Chunk(Base):
    __tablename__ = 'chunks'

    chunk_hash = Column(String(64), primary_key=True)  # SHA-256 hex
    size_bytes = Column(Integer, nullable=False)
    refcount = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    file_mappings = relationship("FileChunk", back_populates="chunk")
    locations = relationship("ChunkLocation", back_populates="chunk",
                             cascade="all, delete-orphan")


# ================================================================
#  FileChunk — ordered mapping from file to content-addressed chunks
#
#  file_id is now a String(36) FK matching File.id (UUID v7).
#  chunk_hash FKs to Chunk.chunk_hash — the canonical record.
#  Multiple files can reference the same chunk_hash (deduplication).
# ================================================================

class FileChunk(Base):
    __tablename__ = 'file_chunks'

    id = Column(Integer, primary_key=True, autoincrement=True)
    file_id = Column(String(36), ForeignKey('files.id', ondelete='CASCADE'), nullable=False)
    chunk_index = Column(Integer, nullable=False)  # Position in file (0, 1, 2...)
    chunk_hash = Column(String(64), ForeignKey('chunks.chunk_hash'), nullable=False)

    file = relationship("File", back_populates="chunk_mappings")
    chunk = relationship("Chunk", back_populates="file_mappings")

    __table_args__ = (
        UniqueConstraint('file_id', 'chunk_index', name='uq_file_chunk_index'),
        Index('ix_file_chunks_hash', 'chunk_hash'),
        Index('ix_file_chunks_file_id', 'file_id'),
    )


# ================================================================
#  ChunkLocation — tracks which nodes physically store which chunks
#
#  chunk_hash FKs to Chunk.chunk_hash.
#  node_id is the node's cryptographic identity string (Ed25519
#  public key hash), NOT a hardcoded integer.
# ================================================================

class ChunkLocation(Base):
    __tablename__ = 'chunk_locations'

    id = Column(Integer, primary_key=True, autoincrement=True)
    chunk_hash = Column(String(64), ForeignKey('chunks.chunk_hash', ondelete='CASCADE'), nullable=False)
    node_id = Column(String, nullable=False)  # Cryptographic node ID

    chunk = relationship("Chunk", back_populates="locations")

    __table_args__ = (
        UniqueConstraint('chunk_hash', 'node_id', name='uq_chunk_node'),
        Index('ix_chunk_locations_hash', 'chunk_hash'),
        Index('ix_chunk_locations_node', 'node_id'),
    )


# ================================================================
#  RaftLogEntry — append-only operation log
#
#  Every metadata write (file create/delete, chunk placement, etc.)
#  is first recorded here as a proposed operation, then applied to
#  the actual tables (File, FileChunk, Chunk, ChunkLocation) only
#  after a quorum of nodes has confirmed the entry.
#
#  Key invariants:
#    - index is cluster-wide, monotonically increasing, never reused
#    - Entries are never updated once written (append-only)
#    - applied=True means this node has written the op to the live tables
#    - payload is canonical JSON with all values baked in at propose time:
#        no datetime.now(), no generate_file_id() at apply time
#    - _apply_single_entry_to_db() is a pure function: given the same entry
#      and the same starting DB state it always produces the same result
#
#  Defined op types:
#    create_file          — insert File row (+ optional FileChunks, Chunks, ChunkLocations)
#    delete_file          — delete File row, decrement chunk refs
#    mark_file_replicated — set File.is_replicated = True
#    add_chunk_location   — insert ChunkLocation row
#    remove_chunk_location — delete ChunkLocation row
#    add_file_chunk       — insert FileChunk row
#    upsert_file_metadata — update or insert File metadata (reconciliation)
# ================================================================

class RaftLogEntry(Base):
    __tablename__ = 'raft_log'

    # Cluster-wide monotonically increasing log index. Never reused.
    index = Column(Integer, primary_key=True)

    # Raft term when this entry was proposed by the leader.
    term = Column(Integer, nullable=False)

    # Operation type string — one of the defined ops above.
    op = Column(String, nullable=False)

    # Canonical JSON payload. All non-deterministic values (timestamps,
    # UUIDs, node IDs) must be baked in here at propose time on the leader.
    # The apply function must never call datetime.now() or generate IDs.
    payload = Column(Text, nullable=False)

    # True once this node has applied the op to the live tables.
    # Entries with applied=False at or below commit_index are pending apply.
    applied = Column(Boolean, nullable=False, default=False)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        # Fast lookup for the apply loop: unapplied entries up to commit_index
        Index('ix_raft_log_applied_index', 'applied', 'index'),
    )


# ================================================================
#  SnapshotMeta — tracks snapshots saved to disk
#
#  One row per snapshot file. Ordered by snapshot_index so the newest
#  snapshot is always findable with a simple DESC query.
#
#  Leaders write a row after _take_snapshot() saves a JSON file.
#  Followers write a row after _apply_snapshot_to_db() installs a
#  received snapshot (file_path is informational — they don't write
#  the JSON themselves, but the path records where it would be).
#
#  _cleanup_old_snapshots() deletes rows (and their JSON files) beyond
#  SNAPSHOT_RETENTION_COUNT, keeping the last N snapshots on disk.
# ================================================================

class SnapshotMeta(Base):
    __tablename__ = 'snapshot_meta'

    id             = Column(Integer, primary_key=True, autoincrement=True)
    snapshot_index = Column(Integer, nullable=False, unique=True)  # raft_log index
    snapshot_term  = Column(Integer, nullable=False)               # term when taken
    file_path      = Column(String,  nullable=False)               # absolute path to JSON
    created_at     = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index('ix_snapshot_meta_index', 'snapshot_index'),
    )


# ================================================================
#  Job / AuditLog — placeholders for future use
# ================================================================

class Job(Base):
    __tablename__ = 'jobs'

    id = Column(Integer, primary_key=True, autoincrement=True)
    type = Column(SQLEnum(JobType), nullable=False)
    status = Column(SQLEnum(JobStatus), default=JobStatus.PENDING)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime, nullable=True)
    details = Column(String, nullable=True)


class AuditLog(Base):
    __tablename__ = 'audit_log'

    id = Column(Integer, primary_key=True, autoincrement=True)
    action = Column(String, nullable=False)
    details = Column(String, nullable=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
