#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# cluster.sh — spin TossIt dev clusters up and down quickly
#
# Usage:
#   ./cluster.sh up [N]          # start N-node cluster (default 3)
#   ./cluster.sh down            # stop cluster and wipe all ephemeral data
#   ./cluster.sh restart [N]     # down then up
#   ./cluster.sh logs [node]     # tail logs (all nodes, or specific one)
#   ./cluster.sh status          # show running nodes and which is leader
#   ./cluster.sh generate N      # print a docker-compose.yml for N nodes
#
# Examples:
#   ./cluster.sh up              # 3-node cluster on ports 8001-8003
#   ./cluster.sh up 5            # 5-node cluster on ports 8001-8005
#   ./cluster.sh down            # wipe everything
#   ./cluster.sh logs node2      # tail node2 only
#   ./cluster.sh generate 5 > docker-compose.yml
# ---------------------------------------------------------------------------

set -euo pipefail

CLUSTER_ID="${TOSSIT_CLUSTER_ID:-deadbeef}"
BASE_PORT="${TOSSIT_BASE_PORT:-8001}"
STORAGE_GB="${TOSSIT_STORAGE_LIMIT_GB:-1}"
PROJECT="${COMPOSE_PROJECT_NAME:-tossit}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

die() { echo "ERROR: $*" >&2; exit 1; }

require_docker() {
  command -v docker &>/dev/null || die "docker not found"
  docker compose version &>/dev/null || die "docker compose plugin not found (need Docker 20.10+)"
}

# Generate an N-node docker-compose.yml to stdout
generate_compose() {
  local n="${1:-3}"

  cat <<EOF
version: "3.9"

# Auto-generated by cluster.sh — $n node cluster
# Cluster ID: $CLUSTER_ID
# All storage is EPHEMERAL (tmpfs). Run './cluster.sh down' to wipe.

networks:
  tossit:
    driver: bridge

services:
EOF

  for i in $(seq 1 "$n"); do
    local port=$(( BASE_PORT + i - 1 ))
    local name="node${i}"

    # Build peer list (all nodes except self)
    local peers=""
    for j in $(seq 1 "$n"); do
      [[ "$j" == "$i" ]] && continue
      peers+="http://node${j}:8000,"
    done
    peers="${peers%,}"  # strip trailing comma

    local first_node="false"
    [[ "$i" == "1" ]] && first_node="true"

    cat <<EOF
  ${name}:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: ${name}
    container_name: ${PROJECT}_${name}
    environment:
      TOSSIT_CLUSTER_ID: "${CLUSTER_ID}"
      TOSSIT_NODE_NAME: "${name}"
      TOSSIT_STORAGE_LIMIT_GB: "${STORAGE_GB}"
      TOSSIT_DATA_DIR: "/data"
      TOSSIT_FIRST_NODE: "${first_node}"
      TOSSIT_PEER_URLS: "${peers}"
    volumes:
      - ${name}_data:/data
    ports:
      - "${port}:8000"
    restart: "no"
    networks:
      - tossit

EOF
  done

  # Named volumes block
  echo "volumes:"
  for i in $(seq 1 "$n"); do
    echo "  node${i}_data:"
  done
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_up() {
  local n="${1:-3}"
  require_docker
  echo "Starting $n-node TossIt cluster (ports $BASE_PORT–$(( BASE_PORT + n - 1 )))..."
  generate_compose "$n" > /tmp/tossit-compose.yml
  docker compose -p "$PROJECT" -f /tmp/tossit-compose.yml up -d --build
  echo ""
  echo "Nodes:"
  for i in $(seq 1 "$n"); do
    echo "  node${i}  →  http://localhost:$(( BASE_PORT + i - 1 ))"
  done
  echo ""
  echo "Run './cluster.sh logs' to follow output."
  echo "Run './cluster.sh down' to stop and wipe all data."
}

cmd_down() {
  require_docker
  if [[ ! -f /tmp/tossit-compose.yml ]]; then
    echo "No active cluster compose file found at /tmp/tossit-compose.yml"
    echo "Trying to stop any running tossit containers..."
    docker ps --filter "name=${PROJECT}_node" -q | xargs -r docker rm -f
    return
  fi
  echo "Stopping cluster and wiping ephemeral data..."
  docker compose -p "$PROJECT" -f /tmp/tossit-compose.yml down -v
  rm -f /tmp/tossit-compose.yml
  echo "Done. All node data wiped."
}

cmd_restart() {
  local n="${1:-3}"
  cmd_down
  cmd_up "$n"
}

cmd_logs() {
  require_docker
  [[ -f /tmp/tossit-compose.yml ]] || die "No active cluster (run './cluster.sh up' first)"
  if [[ -n "${1:-}" ]]; then
    docker compose -p "$PROJECT" -f /tmp/tossit-compose.yml logs -f "$1"
  else
    docker compose -p "$PROJECT" -f /tmp/tossit-compose.yml logs -f
  fi
}

cmd_status() {
  require_docker
  echo "Running TossIt containers:"
  docker ps --filter "name=${PROJECT}_node" --format "  {{.Names}}\t{{.Status}}\t{{.Ports}}"
  echo ""
  echo "Checking leader..."
  # Query each node's health endpoint and report who claims to be leader
  for port in $(seq "$BASE_PORT" $(( BASE_PORT + 9 ))); do
    local resp
    resp=$(curl -sf "http://localhost:${port}/api/health" 2>/dev/null) || continue
    local role; role=$(echo "$resp" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('raft_role','unknown'))" 2>/dev/null)
    local name; name=$(echo "$resp" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('node_name','?'))" 2>/dev/null)
    echo "  localhost:${port}  ($name)  →  $role"
  done
}

cmd_generate() {
  local n="${1:-3}"
  generate_compose "$n"
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

case "${1:-help}" in
  up)       cmd_up "${2:-3}" ;;
  down)     cmd_down ;;
  restart)  cmd_restart "${2:-3}" ;;
  logs)     cmd_logs "${2:-}" ;;
  status)   cmd_status ;;
  generate) cmd_generate "${2:-3}" ;;
  *)
    echo "Usage: $0 {up [N]|down|restart [N]|logs [node]|status|generate N}"
    exit 1
    ;;
esac
